export const MEMES = [
  { src: './assets/preview-images/drake-hotline-bling.jpg',        name: 'Drake' },
  { src: './assets/preview-images/distracted-boyfriend.jpg',        name: 'Distracted Boyfriend' },
  { src: './assets/preview-images/two-buttons.jpg',                 name: 'Two Buttons' },
  { src: './assets/preview-images/change-my-mind.jpg',              name: 'Change My Mind' },
  { src: './assets/preview-images/surprised-pikachu.jpg',           name: 'Surprised Pikachu' },
  { src: './assets/preview-images/roll-safe-think-about-it.jpg',    name: 'Roll Safe' },
  { src: './assets/preview-images/expanding-brain.jpg',             name: 'Galaxy Brain' },
  { src: './assets/preview-images/hide-the-pain-harold.jpg',        name: 'Hide The Pain Harold' },
  { src: './assets/preview-images/one-does-not-simply.jpg',         name: 'One Does Not Simply' },
  { src: './assets/preview-images/disaster-girl.jpg',               name: 'Disaster Girl' },
  { src: './assets/preview-images/this-is-fine.jpg',                name: 'This Is Fine' },
  { src: './assets/preview-images/success-kid.jpg',                 name: 'Success Kid' },
  { src: './assets/preview-images/futurama-fry.jpg',                name: 'Not Sure If' },
  { src: './assets/preview-images/woman-yelling-at-cat.jpg',        name: 'Woman Yelling at Cat' },
  { src: './assets/preview-images/gru-plan.jpg',                    name: 'Gru Plan' },
  { src: './assets/preview-images/mocking-spongebob.jpg',           name: 'Mocking Spongebob' },
  { src: './assets/preview-images/always-has-been.jpg',             name: 'Always Has Been' },
  { src: './assets/preview-images/is-this-a-pigeon.jpg',            name: 'Is This A Pigeon' },
  { src: './assets/preview-images/awkward-look-monkey-puppet.jpg',  name: 'Monkey Puppet' },
  { src: './assets/preview-images/running-away-balloon.jpg',        name: 'Running Away Balloon' },
]
